#!/usr/bin/env python
# encoding: utf-8

"""
teleop.py - Used joy stick messages over /joy to send move commands to the proteus

Created by William Woodall on 2010-04-13.
"""
__author__ = "William Woodall"

###  Imports  ###

# ROS imports
import roslib; roslib.load_manifest('proteus')
import rospy

# ROS msg and srv imports
from proteus.srv import Move
from joy.msg import Joy

def move(speed, direction):
    """Calls the move srv on ax2550_driver.py"""
    try:
        move = rospy.ServiceProxy('move', Move)
        resp1 = move(speed, direction)
        return resp1.result
    except rospy.ServiceException, e:
        rospy.logerr("Service call failed: %s"%e)

def joystickCallback(data):
    """Called everytime the joystick updates"""
    move(data.axes[1], data.axes[0])

def joystickListener():
    """Listens for Joystick signals"""
    rospy.init_node('proteus_teleop', anonymous=True)
    s = rospy.Subscriber('joy', Joy, joystickCallback, queue_size=10)
    rospy.spin()


if __name__ == '__main__':
    joystickListener()
