                                                                                                               /** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : I2C1.C
**     Project   : nick
**     Processor : MC9S12DP512BCPV
**     Beantype  : InternalI2C
**     Version   : Bean 01.200, Driver 01.18, CPU db: 2.87.357
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 9/25/2009, 4:27 PM
**     Abstract  :
**          This bean encapsulates the internal I2C communication 
**          interface. The implementation of the interface is based 
**          on the Philips I2C-bus specification version 2.0. 
**          Interface features:
**          MASTER mode
**            - Multi master communication
**            - The combined format of communication possible 
**              (see "Automatic stop condition" property)
**            - 7-bit slave addressing (10-bit addressing can be made as well)
**            - Acknowledge polling provided
**            - No wait state initiated when a slave device holds the SCL line low
**            - Holding of the SCL line low by slave device recognized as 'not available bus'
**            - Invalid start/stop condition detection provided
**          SLAVE mode
**            - 7-bit slave addressing
**            - General call address detection provided
**     Settings  :
**         Serial channel              : IIC
**
**         Protocol
**             Mode                    : MASTER
**             Auto stop condition     : yes
**             SCL frequency           : 100 kHz
**
**         Initialization
**
**             Target slave address    : 8
**             Bean function           : Enabled
**             Events                  : Enabled
**
**         Registers
**             Input buffer            : IBDR      [228]
**             Output buffer           : IBDR      [228]
**             Control register        : IBCR      [226]
**             Status register         : IBSR      [227]
**             Baud setting reg.       : IBFD      [225]
**             Address register        : IBAD      [224]
**
**         Interrupt
**             Vector name             : Viic
**             Priority                : 1
**
**         Used pins                   :
**       ----------------------------------------------------------
**            Function    | On package |    Name
**       ----------------------------------------------------------
**              SDA       |     99     |  PJ6_RxCAN4_SDA_RxCAN0_KWJ6
**              SCL       |     98     |  PJ7_TxCAN4_SCL_TxCAN0_KWJ7
**       ----------------------------------------------------------
**     Contents  :
**         Enable          - byte I2C1_Enable(void);
**         Disable         - byte I2C1_Disable(void);
**         EnableEvent     - byte I2C1_EnableEvent(void);
**         DisableEvent    - byte I2C1_DisableEvent(void);
**         SendChar        - byte I2C1_SendChar(byte Chr);
**         RecvChar        - byte I2C1_RecvChar(byte *Chr);
**         SendBlock       - byte I2C1_SendBlock(void* Ptr, word Siz, word *Snt);
**         RecvBlock       - byte I2C1_RecvBlock(void* Ptr, word Siz, word *Rcv);
**         GetCharsInTxBuf - word I2C1_GetCharsInTxBuf(void);
**         SelectSlave     - byte I2C1_SelectSlave(byte Slv);
**         GetCharsInRxBuf - word I2C1_GetCharsInRxBuf(void);
**         GetMode         - bool I2C1_GetMode(void);
**         CheckBus        - byte I2C1_CheckBus(void);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE I2C1. */

//#pragma MESSAGE DISABLE C4002          /* Disable warning C4002 "Result not used" */

//#include "Events.h"
#include <mc9s12dp512.h>
//#include "I2C1.h"
#include "i2c_master_intr.h"
#include "LED.h"

//#pragma DATA_SEG I2C1_DATA
//#pragma CODE_SEG I2C1_CODE
/*SerFlag bits*/
#define OVERRUN_ERR      1             /* Overrun error flag bit   */
#define WAIT_RX_CHAR     2             /* Wait for received char. flag bit (Master)  */
#define CHAR_IN_TX       4             /* Char is in TX buffer (Master)    */
#define CHAR_IN_RX       8             /* Char is in RX buffer     */
#define FULL_TX          16            /* Full transmit buffer     */
#define BUSY             32            /* Communication is in progress (Master) */
#define FULL_RX          64            /* Full receive buffer      */
#define MSxSL            128           /* Master x Slave flag bit  */

static unsigned char EnUser;                    /* Enable/Disable device */
volatile unsigned char I2C1_EnEvent;            /* Enable/Disable events */
static unsigned char I2C1_SlaveAddr;            /* Variable for Slave address */
static unsigned short InpLenM;                   /* Length of input bufer's content */
static unsigned char *InpPtrM;                  /* Pointer to input buffer for Master mode */
static unsigned short OutLenM;                   /* Length of output bufer's content */
static unsigned char *OutPtrM;                  /* Pointer to output buffer for Master mode */
volatile unsigned short I2C1_SndRcvTemp;         /* Temporary variable for SendChar (RecvChar) when they call SendBlock (RecvBlock) */
static unsigned char ChrTemp;                   /* Temporary variable for SendChar method */
volatile unsigned char I2C1_SerFlag;            /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Wait for received char. flag bit (Master) */
                                       /*       2 - Char is in TX buffer (Master) */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Master x Slave */
                                       
unsigned char newI2cData = 0; //external signal
unsigned char I2cTransDone = 0; //external signal
                                       

void I2C1_OnReceiveData(void);
void I2C1_OnTransmitData(void);
void I2C1_OnByteTransfer(void);
void I2C1_OnArbitLost(void);
void I2C1_OnNACK(void);

//#pragma MESSAGE DISABLE C4002 /* WARNING C4002: Result not used is ignored */

/*
** ===================================================================
**     Method      :  I2C1_Interrupt (bean InternalI2C)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define RXAK 1
#define SRW  4
#define IBAL 16
#define IAAS 64

#define ON_ARBIT_LOST 1
#define ON_FULL_RX    2
#define ON_RX_CHAR    4
#define ON_FREE_TX    8
#define ON_TX_CHAR    16
#define ON_OVERRUN    32
#define ON_TX_EMPTY   64

//#pragma CODE_SEG __NEAR_SEG NON_BANKED

interrupt 31 void i2c_isr(void)
{
  unsigned char Status = IBSR;                  /* Safe status register */
  LED_BLUE1 ^= 1;
  asm sei
  IBSR_IBIF = 1;                       /* Clear interrupt flag */
  if(IBCR_MS_SL){                      /* Is device in master mode? */
    if (I2C1_EnEvent) {
      I2C1_OnByteTransfer();           /* Invoke OnByteTransfer event */
    }
    if(IBCR_TX_RX){                    /* Is device in Tx mode? */
      if(Status & RXAK) {              /* NACK received? */
        IBCR_MS_SL = 0;                /* Switch device to slave mode (stop signal sent) */
        IBCR_TX_RX = 0;                /* Switch to Rx mode */
        OutLenM = 0;                   /* No character for sending */
        InpLenM = 0;                   /* No character for reception */
        I2C1_SerFlag &= ~(CHAR_IN_TX|WAIT_RX_CHAR|BUSY); /* No character for sending or reception*/
        if (I2C1_EnEvent) {
          // __DI();                     /* Disable maskable interrupts */
          I2C1_OnNACK();               /* Invoke OnNACK event */
        }
      }
      else {
        if(OutLenM) {                  /* Is any char. for transmitting? */
          OutLenM--;                   /* Decrease number of chars for the transmit */
          IBDR = *(OutPtrM)++;         /* Send character */
        }
        else {
          if(InpLenM) {                /* Is any char. for reception? */
            if(InpLenM == 1) {         /* If only one char to receive */
              IBCR_TXAK = 1;           /* then transmit ACK disable */
            }
            else {  //may need to take these comments out
              IBCR_TXAK = 0;           /* else transmit ACK anable */
            }
            IBCR_TX_RX = 0;            /* Switch to Rx mode */
            (void)IBDR;                /* Dummy read character */
          }
          else {
            I2C1_SerFlag &= ~BUSY;     /* Clear flag "busy" */
            //IBCR_MS_SL = 0;            /* Switch device to slave mode (stop signal sent) */
            //IBCR_TX_RX = 0;            /* Switch to Rx mode */
    //added for compass
            IBCR_RSTA = 1;// repeated start
    //end        
            if (I2C1_EnEvent) {
              // __DI();                 /* Disable maskable interrupts */
              I2C1_OnTransmitData();   /* Invoke OnTransmitData event */
            }
          }
        }
      }
    }
    else {
      InpLenM--;                       /* Decrease number of chars for the receive */
      if(InpLenM) {                    /* Is any char. for reception? */
        if(InpLenM == 1) {
          IBCR_TXAK = 1;               /* Transmit ACK disable */
        }
      }
      else {
        IBCR_MS_SL = 0;                /* If no, switch device to slave mode (stop signal sent) */
        IBCR_TX_RX = 0; ///////may not need this
        IBCR_TXAK = 0;                 /* Transmit ACK enable */
      }
      *(InpPtrM)++ = IBDR;             /* Receive character */
      if(!InpLenM) {                   /* Is any char. for reception? */
        if (I2C1_EnEvent) {
         //  __DI();                     /* Disable maskable interrupts */
          I2C1_OnReceiveData();        /* Invoke OnReceiveData event */
        }
      }
    }
  }
  else {
    if(Status & IBAL) {                /* Arbitration lost? */
      OutLenM = 0;                     /* No character for sending */
      InpLenM = 0;                     /* No character for reception */
      I2C1_SerFlag &= ~(CHAR_IN_TX|WAIT_RX_CHAR|BUSY); /* No character for sending or reception*/
      IBCR_TX_RX = 0;                  /* Switch to Rx mode */
      if (I2C1_EnEvent) {
       //  __DI();                       /* Disable maskable interrupts */
        I2C1_OnArbitLost();            /* Invoke OnArbitLost event */
      }
    }
  }
  asm cli
}

//#pragma CODE_SEG I2C1_CODE
/*
** ===================================================================
**     Method      :  I2C1_Enable (bean InternalI2C)
**
**     Description :
**         Enables I2C bean. Events may be generated
**         ("DisableEvent"/"EnableEvent").
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
unsigned char I2C1_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = 1;                     /* If yes then set the flag "device enabled" */
    I2C1_SerFlag &= ~127;              /* Clear the status variable */
    IBCR_IBEN = 1;                     /* Enable device */
    /* IBCR: IBEN=1,IBIE=1,MS_SL=0,TX_RX=0,TXAK=0,RSTA=0,??=0,IBSWAI=0 */
    IBCR = 192;                        /* Control register settings */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_Disable (bean InternalI2C)
**
**     Description :
**         Disables I2C bean. No events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
unsigned char I2C1_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = 0;                    /* If yes then set the flag "device disabled" */
    /* IBCR: IBEN=0,IBIE=0,MS_SL=0,TX_RX=0,TXAK=0,RSTA=0,??=0,IBSWAI=0 */
    IBCR = 0;                          /* Disable device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_EnableEvent (bean InternalI2C)
**
**     Description :
**         Enables the events.
**         This method is enabled only if any event is generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte I2C1_EnableEvent(void)

**  This method is implemented as a macro. See I2C1.h file.  **
*/

/*
** ===================================================================
**     Method      :  I2C1_DisableEvent (bean InternalI2C)
**
**     Description :
**         Disables the events.
**         This method is enabled only if any event is generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte I2C1_DisableEvent(void)

**  This method is implemented as a macro. See I2C1.h file.  **
*/

/*
** ===================================================================
**     Method      :  I2C1_SendChar (bean InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address
**         bytes inclusive of R/W bit = 0 to the I2C bus and then
**         writes one character (byte) to the bus. The slave address
**         must be specified before, by the "SelectSlave" or
**         "SelectSlave10" method or in the bean initialization
**         section, "Target slave address init" property. If
**         interrupt service is enabled and the method returns
**         ERR_OK, it doesn't mean that transmission was successful.
**         The state of transmission is obtainable from
**         (OnTransmitData, OnError or OnArbitLost) events. 
**         When working as a SLAVE, this method writes a character
**         to the internal output slave buffer and, after the master
**         starts the communication, to the I2C bus. If no character
**         is ready for a transmission (internal output slave buffer
**         is empty), the Empty character will be sent (see "Empty
**         character" property).
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by an acknowledge (only
**                           in master mode and when interrupt
**                           service is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot transmit data
**                           ERR_TXFULL - Transmitter is full (slave
**                           mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in
**                           master mode)
** ===================================================================
*/
unsigned char I2C1_SendChar(unsigned char Chr)
{
  if((IBSR_IBB)||(InpLenM)||(I2C1_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|BUSY))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  ChrTemp = Chr;                       /* Save character */
  return (I2C1_SendBlock(&ChrTemp, (unsigned short)1, (unsigned short*)&I2C1_SndRcvTemp)); /* Send character and return */
}

/*
** ===================================================================
**     Method      :  I2C1_RecvChar (bean InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address
**         bytes inclusive of R/W bit = 1 to the I2C bus, then reads
**         one character (byte) from the bus and then sends the stop
**         condition. The slave address must be specified before, by
**         the "SelectSlave" or "SelectSlave10" method or in bean
**         initialization section, property "Target slave address
**         init". If interrupt service is enabled and the method
**         returns ERR_OK, it doesn't mean that transmission was
**         finished successfully. The state of transmission must be
**         tested by means of events (OnReceiveData, OnError or
**         OnArbitLost). In case of successful transmission,
**         received data is ready after OnReceiveData event is
**         called. 
**         When working as a SLAVE, this method reads a character
**         from the input slave buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Received character.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledge
**                           (only in master mode and when interrupt
**                           service is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot receive data
**                           ERR_RXEMPTY - No data in receiver (slave
**                           mode only)
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last character or block
**                           received (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in
**                           master mode)
**                           ERR_NOTAVAIL - Method is not available
**                           in current mode - see generated code
**                           comment
** ===================================================================
*/
/*
byte I2C1_RecvChar(byte *Chr)

**  This method is implemented as a macro. See I2C1.h file.  **
*/

/*
** ===================================================================
**     Method      :  I2C1_SendBlock (bean InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address
**         bytes inclusive of R/W bit = 0 to the I2C bus and then
**         writes the block of characters to the bus. The slave
**         address must be specified before, by the "SelectSlave" or
**         "SlaveSelect10" method or in bean initialization section,
**         "Target slave address init" property. If interrupt
**         service is enabled and the method returns ERR_OK, it
**         doesn't mean that transmission was successful. The state
**         of transmission is detectable by means of events
**         (OnTransmitData, OnError or OnArbitLost). Data to be send
**         is not copied to an internal buffer and remains in the
**         original location. Therefore the content of the buffer
**         should not be changed until the transmission is complete.
**         Event OnTransmitData can be used to detect the end of the
**         transmission.
**         When working as a SLAVE, this method writes a block of
**         characters to the internal output slave buffer and then,
**         after the master starts the communication, to the I2C bus.
**         If no character is ready for a transmission (internal
**         output slave buffer is empty), the "Empty character" will
**         be sent (see "Empty character" property). In SLAVE mode
**         the data are copied to an internal buffer, if specified
**         by "Output buffer size" property.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send.
**         Siz             - Size of the block.
**       * Snt             - Amount of data sent (moved to a buffer).
**                           In master mode, if interrupt support is
**                           enabled, the parameter always returns
**                           the same value as the parameter 'Siz' of
**                           this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledge
**                           (only in master mode and when interrupt
**                           service is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot transmit data
**                           ERR_TXFULL - Transmitter is full. Some
**                           data has not been sent. (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in
**                           master mode)
** ===================================================================
*/
unsigned char I2C1_SendBlock(void* Ptr,unsigned short Siz,unsigned short *Snt)
{
  if (!Siz) {                          /* Test variable Size on zero */
    *Snt = 0;
    return ERR_OK;                     /* If zero then OK */
  }
  if(!EnUser) {                        /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if((IBSR_IBB)||(InpLenM)||(I2C1_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|BUSY))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  //EnterCritical();                     /* Enter the critical section */
  asm sei
  I2C1_SerFlag |= BUSY;                /* Set flag "busy" */
  OutLenM = Siz;                       /* Set lenght of data */
  OutPtrM = (unsigned char *)Ptr;               /* Save pointer to data for transmitting */
  IBCR_TX_RX = 1;                      /* Set TX mode */
  if(IBCR_MS_SL) {                     /* Is device in master mode? */
    IBCR_RSTA = 1;                     /* If yes then repeat start cycle generated */
  }
  else {
    IBCR_MS_SL = 1;                    /* If no then start signal generated */
  }
  IBDR = I2C1_SlaveAddr;               /* Send slave address */
  //ExitCritical();                      /* Exit the critical section */
  asm cli
  *Snt = Siz;                          /* Dummy number of really sent chars */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_RecvBlock (bean InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address
**         bytes inclusive of R/W bit = 1 to the I2C bus, then reads
**         the block of characters from the bus and then sends the
**         stop condition. The slave address must be specified
**         before, by the "SelectSlave" or "SelectSlave10" method or
**         in bean initialization section, "Target slave address
**         init" property. If interrupt service is enabled and the
**         method returns ERR_OK, it doesn't mean that transmission
**         was finished successfully. The state of transmission must
**         be tested by means of events (OnReceiveData, OnError or
**         OnArbitLost). In case of successful transmission,
**         received data is ready after OnReceiveData event is
**         called. 
**         When working as a SLAVE, this method reads a block of
**         characters from the input slave buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block space for
**                           received data.
**         Siz             - The size of the block.
**       * Rcv             - Amount of received data. In master mode,
**                           if interrupt support is enabled, the
**                           parameter always returns the same value
**                           as the parameter 'Siz' of this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by an acknowledge (only
**                           in master mode and when interrupt
**                           service is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot receive data
**                           ERR_RXEMPTY - The receive buffer didn't
**                           contain the requested number of data.
**                           Only available data (or no data) has
**                           been returned  (slave mode only).
**                           ERR_OVERRUN - Overrun error was detected
**                           from last character or block receiving
**                           (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in
**                           master mode)
** ===================================================================
*/
unsigned char I2C1_RecvBlock(void* Ptr,unsigned short Siz,unsigned short *Rcv)
{
  if (!Siz) {                          /* Test variable Size on zero */
    *Rcv = 0;
    return ERR_OK;                     /* If zero then OK */
  }
  if(!EnUser) {                        /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  //if((IBSR_IBB)||(InpLenM)||(I2C1_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|BUSY))) { /* Is the bus busy */
  //  return ERR_BUSOFF;                 /* If yes then error */
  //}
  //EnterCritical();                     /* Enter the critical section */
  asm sei
  InpLenM = Siz;                       /* Set lenght of data */
  InpPtrM = (unsigned char *)Ptr;               /* Save pointer to data for reception */
  IBCR_TX_RX = 1;                      /* Set TX mode */
  if(IBCR_MS_SL) {                     /* Is device in master mode? */
    IBCR_RSTA = 1;                     /* If yes then repeat start cycle generated */
  }
  else {
    IBCR_MS_SL = 1;                    /* If no then start signal generated */
  }
  IBDR = (unsigned char)(I2C1_SlaveAddr+1);     /* Send slave address */
  //ExitCritical();                      /* Exit the critical section */
  asm cli
  *Rcv = Siz;                          /* Dummy number of really received chars */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_GetCharsInTxBuf (bean InternalI2C)
**
**     Description :
**         Returns number of characters in the output buffer. In
**         SLAVE mode returns the number of characters in the
**         internal slave output buffer. In MASTER mode returns
**         number of characters to be sent from the user buffer
**         (passed by SendBlock method).
**         This method is not supported in polling mode.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output
**                           buffer.
** ===================================================================
*/
unsigned short I2C1_GetCharsInTxBuf(void)
{
  return(OutLenM);                     /* Return number of chars remaining in the Master Tx buffer */
}

/*
** ===================================================================
**     Method      :  I2C1_GetCharsInRxBuf (bean InternalI2C)
**
**     Description :
**         Returns number of characters in the input buffer. In
**         SLAVE mode returns the number of characters in the
**         internal slave input buffer. In MASTER mode returns
**         number of characters to be received into a user buffer
**         (passed by RecvChar or RecvBlock method).
**         This method is not supported in polling mode.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input
**                           buffer.
** ===================================================================
*/
unsigned short I2C1_GetCharsInRxBuf(void)
{
  return(InpLenM);                     /* Return number of chars remaining in the Master Tx buffer */
}

/*
** ===================================================================
**     Method      :  I2C1_SelectSlave (bean InternalI2C)
**
**     Description :
**         This method selects a new slave for communication by its
**         7-bit slave address value. Any send or receive method
**         directs to or from selected device, until a new slave
**         device is selected by this method. This method is not
**         available for the SLAVE mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Slv             - 7-bit slave address value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_BUSY - The device is busy, wait
**                           until the current operation is finished.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  The device is disabled
** ===================================================================
*/
unsigned char I2C1_SelectSlave(unsigned char Slv)
{
  //LED_redOn();
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (IBCR_MS_SL == 1) {               /* Is the device in the active state? */
    return ERR_BUSY;                   /* If yes then error */
  }
  //LED_greenOn();
  I2C1_SlaveAddr = (unsigned char)(Slv << 1);   /* Set slave address */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_GetMode (bean InternalI2C)
**
**     Description :
**         This method returns the actual operating mode of this
**         bean.
**     Parameters  : None
**     Returns     :
**         ---             - Actual operating mode value
**                           TRUE - Master
**                           FALSE - Slave
** ===================================================================
*/
/*
bool I2C1_GetMode(void)

**  This method is implemented as a macro. See I2C1.h file.  **
*/

/*
** ===================================================================
**     Method      :  I2C1_Init (bean InternalI2C)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void I2C1_Init(void)
{
  /* IBCR: IBEN=0,IBIE=0,MS_SL=0,TX_RX=0,TXAK=0,RSTA=0,??=0,IBSWAI=0 */
  IBCR = 0;                            /* Clear control register */
  I2C1_SerFlag = 128;                  /* Reset all flags */
  I2C1_EnEvent = 1;                 /* Enable events */
  EnUser = 1;                       /* Enable device */
  I2C1_SlaveAddr = 16;                 /* Set variable for slave address */
  /* IBFD: IBC7=0,IBC6=0,IBC5=0,IBC4=1,IBC3=1,IBC2=1,IBC1=1,IBC0=1 */
  IBFD = 31;                           /* Set prescaler bits */
  IBCR_IBEN = 1;                       /* Enable device */
  /* IBCR: IBEN=1,IBIE=1,MS_SL=0,TX_RX=0,TXAK=0,RSTA=0,??=0,IBSWAI=0 */
  IBCR = 192;                          /* Control register settings */
  InpLenM = 0;                 
  OutLenM = 0;
}

/*
** ===================================================================
**     Method      :  I2C1_CheckBus (bean InternalI2C)
**
**     Description :
**         This method returns the status of the bus. If the START
**         condition has been detected, the method returns
**         'BeanName'_BUSY. If the STOP condition has been detected,
**         the method returns 'BeanName'_IDLE.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the bus.
** ===================================================================
*/
/*
byte I2C1_CheckBus(void)

**  This method is implemented as a macro. See I2C1.h file.  **
*/


/* END I2C1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.99 [04.12]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/












/*********************************events************************/









void I2C1_OnReceiveData(void){
  newI2cData = 1;
}
/*
** ===================================================================
**     Event       :  I2C1_OnReceiveData (module Events)
**
**     From bean   :  I2C1 [InternalI2C]
**     Description :
**         This event is invoked when I2C finishes the reception of
**         the data successfully. This event is not available for
**         the SLAVE mode and if both RecvChar and RecvBlock are
**         disabled. This event is enabled only if interrupts/events
**         are enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void I2C1_OnTransmitData(void){
  I2cTransDone = 1;
}
/*
** ===================================================================
**     Event       :  I2C1_OnTransmitData (module Events)
**
**     From bean   :  I2C1 [InternalI2C]
**     Description :
**         This event is invoked when I2C finishes the transmission
**         of the data successfully. This event is not available for
**         the SLAVE mode and if both SendChar and SendBlock are
**         disabled. This event is enabled only if interrupts/events
**         are enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/


void I2C1_OnByteTransfer(void){
  
}
/*
** ===================================================================
**     Event       :  I2C1_OnByteTransfer (module Events)
**
**     From bean   :  I2C1 [InternalI2C]
**     Description :
**         This event is called when one-byte transfer (including
**         the acknowledge bit) is successfully finished (slave
**         address or one data byte is transmitted or received).
**         This event is not available for the SLAVE mode and if all
**         RecvChar, RecvBlock, SendChar and SendBlock are disabled.
**         Note: It is possible to use the event for slowing down
**         communication, when slower slave needs some time for data
**         processing.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void I2C1_OnArbitLost(void){
}
/*
** ===================================================================
**     Event       :  I2C1_OnArbitLost (module Events)
**
**     From bean   :  I2C1 [InternalI2C]
**     Description :
**         This event is called when the master lost the bus
**         arbitration or the device detects an error on the bus.
**         This event is enabled only if interrupts/events are
**         enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void I2C1_OnNACK(void){
}
/*
** ===================================================================
**     Event       :  I2C1_OnNACK (module Events)
**
**     From bean   :  I2C1 [InternalI2C]
**     Description :
**         Called when a no slave acknowledge (NAK) occurs during
**         communication. This event is not available for the SLAVE
**         mode. This event is enabled only if interrupts/events are
**         enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/


/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.99 [04.12]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
















